### PR TITLE
Add link to corresponding help.github.com article

### PR DESCRIPTION
**Pull request by aiwebb**

### CODE REVIEW

**Comment by benbalter** [comment]
Thanks @aiwebb!

**Comment by haaami01** [comment]
Thank you for the opportunity, update has been made. 😊

**Comment by lyric-k** [comment]
9e45d696c2a9badd8865fd954d274b040e77dff8

**Review by lyric-k — COMMENTED** [review]
Thank you ^^**🤗

**Comment by 0867085052** [comment]
Hi.

**Comment by hayya33** [comment]
Hayyas77

**Comment by haaami01** [comment]
hi

**Comment by shankarom700** [comment]
[](url)
Week #13 recap from The CapTable - Secondary exits vs IPOs, India’s Thrasio will be different, Nithin Kamath interview, & more
snapshot_www facebook com_1622616343132
@Navhyanikhilwebpoints

**Review by lyric-k — COMMENTED** [review]
Thank you so much:)

**Review by Emacewosc — COMMENTED** [review]
https://github.com/github/.github/pull/1#issuecomment-812800200

**Review by Emacewosc — COMMENTED** [review]
PISZE

**Review by Emacewosc — COMMENTED** [review]
PISZE

**Review by cesarzer — APPROVED** [review]

**Comment by 1096103013** [comment]
> 

- - [ ] @haaami01 _***_

**Pull request merged**
