### PR TITLE
Update SECURITY.md

### PR DESCRIPTION
**Pull request by Mk1206mk**
[GitHub Actions CI](https://github.com/github/opensource.guide/actions/workflows/tests.yml)

### CODE REVIEW

**Review by Marion455 — APPROVED** [review]

**Comment by Lerzsta** [comment]
Lerz

**Comment by Tomyleexrp** [comment]
profile/README.md

**Comment by Tomyleexrp** [comment]
github:master

**Comment by Tomyleexrp** [comment]
gh pr checkout 213

**Comment by zkoppert** [comment]
We don't want to put CI information in the `SECURITY.md`

**Pull request closed without merging**
