### PR TITLE
Include desktop in open source projects

### PR DESCRIPTION
**Pull request by ahpook**
Per @mxie, let's include desktop in our list of open source projects

### CODE REVIEW

**Review by mxie — APPROVED** [review]
Thank you!! 💖

**Review by zkoppert — APPROVED** [review]

**Comment by Hulusi686** [comment]
[]()

**Review by nafeef123 — COMMENTED** [review]
Approved

**Review by 2741397 — APPROVED** [review]

**Review by Reality2byte — COMMENTED** [review]
#562

**Review by yxftjv4mq7-code — COMMENTED** [review]
Shaker

**Comment by Hulusi686** [comment]
``https://github.com/github/.github/pull/463#pullrequestreview-3736705646

**Pull request merged**
