### PR TITLE
 Hacker Mũ Trắng

### PR DESCRIPTION
**Pull request by TuanPm86**
I am very passionate about creative exploration and learning and gaining experience in security skills for the largest social networking applications of the developers.

### CODE REVIEW

**Comment by TuanPm86** [comment]
Tôi tự tin tìm ra lỗi bảo mật hệ thống máy chủ Facebook Google

**Review by Adiltonzsl — APPROVED** [review]

**Comment by Adiltonzsl** [comment]
aferreira:host-check-config

**Comment by TANATNATH** [comment]
https://github.com/github/.github/pull/88

**Pull request closed without merging**
