### PR TITLE
Fixed incorrect link in SECURITY.md

### PR DESCRIPTION
**Pull request by justinhartman**
- Fixed link to targets from `#scope` to `#targets`.
- Cleaned up formatting and links in the document.

### CODE REVIEW

**Comment by VChernomYA** [comment]
justinhartman:patch-1

**Comment by VChernomYA** [comment]
justinhartman:patch-1

**Comment by chayano** [comment]
gh pr checkout 11

**Comment by chayano** [comment]
gh pr checkout 11

**Review by 5523119376 — APPROVED** [review]

**Comment by ashtont8** [comment]
> SECURITY.md

**Comment by ashtont8** [comment]
>  @#``

**Comment by ashtont8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________________________________________________________
Join Microsoft Teams Meeting<https://teams.microsoft.com/l/meetup-join/19%3ameeting_MTUyNGZiNTctNTk1YS00MGUxLTlmYTItMjY2ZDFlMzViMjA1%40thread.v2/0?context=%7b%22Tid%22%3a%22baf8218e-b302-4465-a993-4a39c97251b2%22%2c%22Oid%22%3a%224e93275f-e6b7-492d-bfac-b974d39fd044%22%7d>
+1 434-219-5359<tel:+1%20434-219-5359,,371626012#>   United States, Lynchburg (Toll)
Conference ID: 371 626 012#
Local numbers<https://dialin.teams.microsoft.com/e17f9616-1136-4be3-a2fe-eff3e5f4b4b7?id=371626012> | Reset PIN<https://mysettings.lync.com/pstnconferencing> | Learn more about Teams<https://aka.ms/JoinTeamsMeeting> | Meeting options<https://teams.microsoft.com/meetingOptions/?organizerId=4e93275f-e6b7-492d-bfac-b974d39fd044&tenantId=baf8218e-b302-4465-a993-4a39c97251b2&threadId=19_meeting_MTUyNGZiNTctNTk1YS00MGUxLTlmYTItMjY2ZDFlMzViMjA1@thread.v2&messageId=0&language=en-US>
________________________________________________________________________________

**Comment by ashtont8** [comment]
#1

**Comment by ashtont8** [comment]
Hi,

I am experiencing connection problems using the harmon.ie app.

I’ve encountered an error while connecting to my Office 365 account.
For more information: https://harmon.ie/support

Can you please help me sort this out?

------------------
Operating system: Mac/iOS
Browser: Safari 14
Client time: Sun Oct 04 2020 09:34:19 GMT-0500 (CDT)


Sent from my iPhone

**Comment by ashtont8** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by djmareewish — CHANGES_REQUESTED** [review]
#1 @justinhartman

**Comment by ikeedge** [comment]
> * Fixed link to targets from `#scope` to `#targets`.
> * Cleaned up formatting and links in the document.

Z

**Review by ikeedge — APPROVED** [review]

**Comment by jace4511** [comment]
-----BEGIN PGP MESSAGE-----

hQIMA7TlqkAVGpiPARAAo1OLbIbZab3/SU8pbmv2LfaPuJZLZ01rRjOUuVu6Y39S
FNDUQ4IaIO+44g/rlTsYNg4D7p/ftzR9Iv5lfFrsyRhD6YNjgBikhSXVU6VlKyKO
U1aXFrPNckNfOS+4Ez3hk3ALFzDQwX5uNQuHahq4GEhekDUDlNKMyr6/bSbWchp7
GdsJzesR5wypcsx92PMSLGGpH23uYlOKPihGRokDlQqINaZlveVkufnuGyWfJMPK
ei5CfYTOxEaRfTOol2y1xUp2Z6NGGFAwmB2KVwl98xEq1ZdJcdf9enFLMwP8noHy
TdG1FODkjOhmIKHwJaiQfmewvUNTX6x7dWoOGf3giXOIeEhRupmu63WxS8dgN0MH
8rWkILQ0DGGoa3p4euIGaN5xHMXMxrYMMISgM0KZYXm+pjN3BHrW//URV1sS+b/Z
wZps3ssL94FkH222Xtg9/zsUO3R6cMOL3KawxUyQ4skVwWNvjQw51ci66oKjZ06K
jKsPJEq8Z0QIntM/OOZRLpBela9Kh3+QbN6VmGjj3Niw3/enLXxGcVcMr/QWyYPA
Pts8bh5YgQJHGuJ0nX4OM/ifFWB+1XOvyJUUCSpNtdUJclM2rWbYi6stjRmRsTYZ
UCUOAwiXUY8wsYjSnjwL8JhbVuOmVmuwXfMdh1UyJhGMSMmefWFe6uwMBLg5r7PS
wKwBP13enrrjyo7Ma2T129oiYrB/eKW9xjzxrp+9YtEbT0Sytxq5vmFyu830b9qN
oBE5xySUXx7jZTsujAbWxj5dXjpVcrJnNAMheem5VcDdnaJLW2d5tlNbhZF2E+hO
4IlCbljLb73A+teur1t0Sr01hzHKUlvXUPtf1O6tRItIMhxj4sCsUoys6tkeq6nV
zPW+RBen7eBGcW47p+qhsBEDtIEoJ/aruOyxLP8G343rgHbrYPafjr1V1wRhH0VK
y3QHTlMPhwpODrM8aGK1t6X0kkTnNF8BhCpBqP/mxUzEWdc1WApySS3MmyK5eeCE
nOMbGePbzdE+tlzrQZMlvwz/9nviYJj4j+KtWqfZQ2kFdGC2uvViTIbxGzyZ+n35
//NE9JbgtwWG1XCJOoZ1YVqdV/sPnPCAo63QkV/YWyKPRo20vzhwogSt6A0cQ809
FeZ6Xkkzn3S4sJ9/T7YnutmCWRZ/YwtsZSyzPRZf
=zFqG
-----END PGP MESSAGE-----

**Comment by jace4511** [comment]
-----BEGIN PGP MESSAGE-----

hQIMA7TlqkAVGpiPARAAo1OLbIbZab3/SU8pbmv2LfaPuJZLZ01rRjOUuVu6Y39S
FNDUQ4IaIO+44g/rlTsYNg4D7p/ftzR9Iv5lfFrsyRhD6YNjgBikhSXVU6VlKyKO
U1aXFrPNckNfOS+4Ez3hk3ALFzDQwX5uNQuHahq4GEhekDUDlNKMyr6/bSbWchp7
GdsJzesR5wypcsx92PMSLGGpH23uYlOKPihGRokDlQqINaZlveVkufnuGyWfJMPK
ei5CfYTOxEaRfTOol2y1xUp2Z6NGGFAwmB2KVwl98xEq1ZdJcdf9enFLMwP8noHy
TdG1FODkjOhmIKHwJaiQfmewvUNTX6x7dWoOGf3giXOIeEhRupmu63WxS8dgN0MH
8rWkILQ0DGGoa3p4euIGaN5xHMXMxrYMMISgM0KZYXm+pjN3BHrW//URV1sS+b/Z
wZps3ssL94FkH222Xtg9/zsUO3R6cMOL3KawxUyQ4skVwWNvjQw51ci66oKjZ06K
jKsPJEq8Z0QIntM/OOZRLpBela9Kh3+QbN6VmGjj3Niw3/enLXxGcVcMr/QWyYPA
Pts8bh5YgQJHGuJ0nX4OM/ifFWB+1XOvyJUUCSpNtdUJclM2rWbYi6stjRmRsTYZ
UCUOAwiXUY8wsYjSnjwL8JhbVuOmVmuwXfMdh1UyJhGMSMmefWFe6uwMBLg5r7PS
wKwBP13enrrjyo7Ma2T129oiYrB/eKW9xjzxrp+9YtEbT0Sytxq5vmFyu830b9qN
oBE5xySUXx7jZTsujAbWxj5dXjpVcrJnNAMheem5VcDdnaJLW2d5tlNbhZF2E+hO
4IlCbljLb73A+teur1t0Sr01hzHKUlvXUPtf1O6tRItIMhxj4sCsUoys6tkeq6nV
zPW+RBen7eBGcW47p+qhsBEDtIEoJ/aruOyxLP8G343rgHbrYPafjr1V1wRhH0VK
y3QHTlMPhwpODrM8aGK1t6X0kkTnNF8BhCpBqP/mxUzEWdc1WApySS3MmyK5eeCE
nOMbGePbzdE+tlzrQZMlvwz/9nviYJj4j+KtWqfZQ2kFdGC2uvViTIbxGzyZ+n35
//NE9JbgtwWG1XCJOoZ1YVqdV/sPnPCAo63QkV/YWyKPRo20vzhwogSt6A0cQ809
FeZ6Xkkzn3S4sJ9/T7YnutmCWRZ/YwtsZSyzPRZf
=zFqG
-----END PGP MESSAGE-----

**Comment by jace4511** [comment]
-----BEGIN PGP MESSAGE-----

hQIMA7TlqkAVGpiPARAAo1OLbIbZab3/SU8pbmv2LfaPuJZLZ01rRjOUuVu6Y39S
FNDUQ4IaIO+44g/rlTsYNg4D7p/ftzR9Iv5lfFrsyRhD6YNjgBikhSXVU6VlKyKO
U1aXFrPNckNfOS+4Ez3hk3ALFzDQwX5uNQuHahq4GEhekDUDlNKMyr6/bSbWchp7
GdsJzesR5wypcsx92PMSLGGpH23uYlOKPihGRokDlQqINaZlveVkufnuGyWfJMPK
ei5CfYTOxEaRfTOol2y1xUp2Z6NGGFAwmB2KVwl98xEq1ZdJcdf9enFLMwP8noHy
TdG1FODkjOhmIKHwJaiQfmewvUNTX6x7dWoOGf3giXOIeEhRupmu63WxS8dgN0MH
8rWkILQ0DGGoa3p4euIGaN5xHMXMxrYMMISgM0KZYXm+pjN3BHrW//URV1sS+b/Z
wZps3ssL94FkH222Xtg9/zsUO3R6cMOL3KawxUyQ4skVwWNvjQw51ci66oKjZ06K
jKsPJEq8Z0QIntM/OOZRLpBela9Kh3+QbN6VmGjj3Niw3/enLXxGcVcMr/QWyYPA
Pts8bh5YgQJHGuJ0nX4OM/ifFWB+1XOvyJUUCSpNtdUJclM2rWbYi6stjRmRsTYZ
UCUOAwiXUY8wsYjSnjwL8JhbVuOmVmuwXfMdh1UyJhGMSMmefWFe6uwMBLg5r7PS
wKwBP13enrrjyo7Ma2T129oiYrB/eKW9xjzxrp+9YtEbT0Sytxq5vmFyu830b9qN
oBE5xySUXx7jZTsujAbWxj5dXjpVcrJnNAMheem5VcDdnaJLW2d5tlNbhZF2E+hO
4IlCbljLb73A+teur1t0Sr01hzHKUlvXUPtf1O6tRItIMhxj4sCsUoys6tkeq6nV
zPW+RBen7eBGcW47p+qhsBEDtIEoJ/aruOyxLP8G343rgHbrYPafjr1V1wRhH0VK
y3QHTlMPhwpODrM8aGK1t6X0kkTnNF8BhCpBqP/mxUzEWdc1WApySS3MmyK5eeCE
nOMbGePbzdE+tlzrQZMlvwz/9nviYJj4j+KtWqfZQ2kFdGC2uvViTIbxGzyZ+n35
//NE9JbgtwWG1XCJOoZ1YVqdV/sPnPCAo63QkV/YWyKPRo20vzhwogSt6A0cQ809
FeZ6Xkkzn3S4sJ9/T7YnutmCWRZ/YwtsZSyzPRZf
=zFqG
-----END PGP MESSAGE-----

**Review by sickwithitallday1 — APPROVED** [review]

**Review by Kkhk54 — APPROVED** [review]

**Review by jace4511 — COMMENTED** [review]
You can find useful information in our [rules][gh-rules],
[scope][gh-scope], [targets][gh-target] and [FAQ][gh-faq].

[//]: # (Links to references above.)

[hackerone]: https://hackerone.com/github
[gh-rules]: https://bounty.github.com/#rules
[gh-scope]: https://bounty.github.com/#scope
[gh-target]: https://bounty.github.com/#targets
[gh-faq]: https://bounty.github.com/#faqs

**Comment by GAMITROHAN** [comment]
About! Lesa often as I can do it for a natural resources.

**Review by jace4511 — APPROVED** [review]

**Comment by Gothicania** [comment]
> * Fixed link to targets from `#scope` to `#targets`.
> * Cleaned up formatting and links in the document.

**Review by Dannell77 — APPROVED** [review]

**Review by akkarapon26 — APPROVED** [review]

**Review by akkarapon26 — APPROVED** [review]

**Comment by jadeybaby79** [comment]
Lisa u fucking slut so u were fuckingv my man behind my back u knew he was with me u slut and brendon ur a cunt u touched my daughter I've got papers saying ur not aloud near kids drinking ur a sick fuck and lisa I'm gonna knock ya teeth out cheating slut

**Review by jonathanmcmillan51 — APPROVED** [review]

**Comment by jonathanmcmillan51** [comment]
#11

**Comment by jonathanmcmillan51** [comment]
#12 
#11 #1

**Review by jonathanmcmillan51 — APPROVED** [review]

**Comment by lyric-k** [comment]
@jonathanmcmillan51

**Comment by lyric-k** [comment]
Why is this a threat?

**Review by jonathanmcmillan51 — APPROVED** [review]
#11 #43 #1 #37 #12 #1

**Review by aliceinspace — APPROVED** [review]

**Review by aliceinspace — APPROVED** [review]

**Comment by justinhartman** [comment]
Closing this because the content has changed since this was originally submitted in July 2020.

**Pull request closed without merging**
